version: 2
updates:
- package-ecosystem: yarn
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: beta
  labels:
    - type/dependencies
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
